window.DRreddit = window.DRreddit || {};

Object.defineProperty(window.DRreddit, 'NAMES', {
    value: [null,
        "Monokuma",
        "Usami",
        "Monomi",
        "Aoi Asahina",
        "Celestia Ludenberg",
        "Junko Enoshima",
        "Chihiro Fujisaki",
        "Touko Fukawa",
        "Genocider Shou",
        "Yasuhiro Hagakure",
        "Mukuro Ikusaba",
        "Mukuro Ikusaba",
        "Kiyotaka Ishimaru",
        "Kyouko Kirigiri",
        "Leon Kuwata",
        "Sayaka Maizono",
        "Makoto Naegi",
        "Sakura Oogami",
        "Mondo Oowada",
        "Byakuya Togami",
        "Hifumi Yamada",
        "Teruteru Hanamura",
        "Hajime Hinata",
        "Mahiru Koizumi",
        "Fuyuhiko Kuzuryuu",
        "Nagito Komaeda",
        "Ibuki Mioda",
        "Chiaki Nanami",
        "Nekomaru Nidai",
        "Robo-Nekomaru Nidai",
        "Akane Owari",
        "Peko Pekoyama",
        "Hiyoko Saionji",
        "Sonia Nevermind",
        "Kazuichi Souda",
        "Gundham Tanaka",
        "Mikan Tsumiki",
        "Not Byakuya Togami",
        "Komaru Naegi"
    ],
    writable: false
})

Object.defineProperty(window.DRreddit, 'ROLES', {
    value: {
        MONOKUMA: 1,
        USAMI: 2,
        MONOMI: 3,
        AOI: 4,
        CELES: 5,
        JUNKO: 6,
        CHIHIRO: 7,
        TOUKO: 8,
        GENOCIDER: 9,
        YASUHIRO: 10,
        MUKURO: 11,
        JUNKOSABA: 12,
        KIYOTAKA: 13,
        KYOUKO: 14,
        LEON: 15,
        SAYAKA: 16,
        MAKOTO: 17,
        SAKURA: 18,
        MONDO: 19,
        BYAKUYA: 20,
        HIFUMI: 21,
        TERUTERU: 22,
        HAJIME: 23,
        MAHIRU: 24,
        FUYUHIKO: 25,
        NAGITO: 26,
        IBUKI: 27,
        CHIAKI: 28,
        NEKOMARU: 29,
        MECHAMARU: 30,
        AKANE: 31,
        PEKO: 32,
        HIYOKO: 33,
        SONIA: 34,
        KAZUICHI: 35,
        GUNDHAM: 36,
        MIKAN: 37,
        IMPOSTER: 38,
        KOMARU: 39
    },
    writable: false
});