window.DRreddit = window.DRreddit || {};

Object.defineProperty(window.DRreddit, "NAMES", {
	value: [
		null,
		"Monokuma",
		"Usami",
		"Monomi",
		"Kurokuma",
		"Shirokuma",
		"Alter Ego",
		"Aoi Asahina",
		"Celestia Ludenberg",
		"Junko Enoshima",
		"Chihiro Fujisaki",
		"Touko Fukawa",
		"Genocider Shou",
		"Yasuhiro Hagakure",
		"Mukuro Ikusaba",
		"Mukuro Ikusaba",
		"Kiyotaka Ishimaru",
		"Kyouko Kirigiri",
		"Leon Kuwata",
		"Sayaka Maizono",
		"Makoto Naegi",
		"Sakura Oogami",
		"Mondo Oowada",
		"Byakuya Togami",
		"Hifumi Yamada",
		"Teruteru Hanamura",
		"Hajime Hinata",
		"Mahiru Koizumi",
		"Fuyuhiko Kuzuryuu",
		"Nagito Komaeda",
		"Ibuki Mioda",
		"Chiaki Nanami",
		"Nekomaru Nidai",
		"Robo-Nekomaru Nidai",
		"Akane Owari",
		"Peko Pekoyama",
		"Hiyoko Saionji",
		"Sonia Nevermind",
		"Kazuichi Souda",
		"Gundham Tanaka",
		"Mikan Tsumiki",
		"Not Byakuya Togami",
		"Komaru Naegi",
		"Almost Kiyotaka Ishimaru",
		"Yui Samidare",
		"Ryouko Otonashi",
		"Yasuke Matsuda",
		"Kamishiro Yuuto",
		"Number between 1 and 8-shiki Madarai",
		"Santa Shikiba",
		"Masaru Daimon",
		"Jatarou Kemuri",
		"Kotoko Utsugi",
		"Nagisa Shingetsu",
		"Monaca Towa",
		"Haiji Towa",
		"Taichi Fujisaki",
		"Hiroko Hagakure",
		"Yuuta Asahina",
		"Kenishiro",
		"Izuru Kamukura",
		"Hajime Hinata plugged-in",
		"Natsumi Kuzuryuu",
		"Chisa Yukizome",
		"Juuzo Sakakura",
		"Kyousuke Munakata",
		"Angie Yonaga",
		"Gonta Gokuhara",
		"Himiko Yumeno",
		"Kaede Akamatsu",
		"Kaito Momota",
		"K1-B0, \"Keebo\"",
		"Kirumi Tojo",
		"Kokichi Ouma",
		"Korekiyo Shinguji",
		"Maki Harukawa",
		"Miu Iruma",
		"Monodam",
		"Monokid",
		"Monophanie",
		"Monosuke",
		"Monotaro",
		"Rantaro Amami",
		"Ryouma Hoshi",
		"Shuichi Saihara",
		"Tenko Chabashira",
		"Tsumugi Shirogane",
	],
	writable: true
});

Object.defineProperty(window.DRreddit, "SPRITES", {
	value: [null],
	writable: true
});

Object.defineProperty(window.DRreddit, "ROLES", {
	value: {
		MONOKUMA: 1,
		USAMI: 2,
		MONOMI: 3,
		KUROKUMA: 4,
		SHIROKUMA: 5,
		ALTEREGO: 6,
		AOI: 7,
		CELES: 8,
		JUNKO: 9,
		CHIHIRO: 10,
		TOUKO: 11,
		GENOCIDER: 12,
		YASUHIRO: 13,
		MUKURO: 14,
		JUNKOSABA: 15,
		KIYOTAKA: 16,
		KYOUKO: 17,
		LEON: 18,
		SAYAKA: 19,
		MAKOTO: 20,
		SAKURA: 21,
		MONDO: 22,
		BYAKUYA: 23,
		HIFUMI: 24,
		TERUTERU: 25,
		HAJIME: 26,
		MAHIRU: 27,
		FUYUHIKO: 28,
		NAGITO: 29,
		IBUKI: 30,
		CHIAKI: 31,
		NEKOMARU: 32,
		MECHAMARU: 33,
		AKANE: 34,
		PEKO: 35,
		HIYOKO: 36,
		SONIA: 37,
		KAZUICHI: 38,
		GUNDHAM: 39,
		MIKAN: 40,
		IMPOSTER: 41,
		KOMARU: 42,
		ISHIDA: 43,
		YUI: 44,
		RYOUKO: 45,
		YASUKE: 46,
		KAMISHIRO: 47,
		MADARAI: 48,
		SANTA: 49,
		MASARU: 50,
		JATAROU: 51,
		KOTOKO: 52,
		NAGISA: 53,
		MONACA: 54,
		HAIJI: 55,
		TAICHI: 56,
		HIROKO: 57,
		YUUTA: 58,
		KENISHIRO: 59,
		IZURU: 60,
		SAIYANHAJIME: 61,
		NATSUMI: 62,
		CHISA: 63,
		JUUZOU: 64,
		KYOUSUKE: 65,
		ANGIE: 66,
		GONTA: 67,
		HIMIKO: 68,
		KAEDE: 69,
		KAITO: 70,
		KEEBO: 71,
		KIRUMI: 72,
		KOKICHI: 73,
		KOREKIYO: 74,
		MAKI: 75,
		MIU: 76,
		MONODAM: 77,
		MONOKID: 78,
		MONOPHANIE: 79,
		MONOSUKE: 80,
		MONOTARO: 81,
		RANTARO: 82,
		RYOMA: 83,
		SHUICHI: 84,
		TENKO: 85,
		TSUMUGI: 86,
		assign: function(constant) {
			var code = Object.keys(this).length;
			constant =
				constant.replace(/\W/g, "").toUpperCase() +
				Math.ceil(Math.random() * 1000);

			this[constant] = code;

			return {
				key: constant,
				code: code
			};
		}
	},
	writable: false
});
